name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'beta/**'
      - 'feature/**'
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]

env:
  REGISTRY: gitea.local.coddicted.com
  IMAGE_NAME: mobo-backend

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: mobo_ci
          POSTGRES_PASSWORD: mobo_ci_pass
          POSTGRES_DB: mobo_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U mobo_ci"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      DATABASE_URL: postgresql://mobo_ci:mobo_ci_pass@localhost:5432/mobo_ci
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint backend
        run: npm -w @mobo/backend run lint

      - name: Generate Prisma client
        run: npm -w @mobo/backend run pg:generate

      - name: Build backend
        run: npm -w @mobo/backend run build

      - name: Run backend tests
        run: npm -w @mobo/backend run test

  docker-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ gitea.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: |
          echo "✅ Image pushed successfully!"
          echo "🏷️ Tags: ${{ steps.meta.outputs.tags }}"
